# Generated by Django 4.2.3 on 2023-07-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('orderName', models.CharField(max_length=300)),
                ('orderTotal', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('deliveryType', models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Delivery')], max_length=10)),
                ('totalcost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
